### ISSUE TITLE
Recent changes breaking simplewing function

### ISSUE THREAD

**Issue by jjohns99** [byuflowlab/VLM.jl#6]
A recent commit to `geometry.jl` is causing the `simplewing` function to break. The `linearsections` function was renamed to `linear_sections`, but the call was not changed in `simplewing` or `export linearsections`.

**Comment by andrewning** [comment]
@taylormcd

**Comment by taylormcd** [comment]
Just pushed to the master branch the fix for this.  Note, however, that some of the inputs to `simplewing` have changed as a result of #5 .  Also, just as a warning, I'm currently focused pretty heavily on developing this package, so expect more breaking changes in the near future.
